title: Tips to protest safely
description: >-
  WTF do I bring to protest? WTF do I do at a protest?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lede: "Going to a protest or action? This resource aims to provide you with information to prepare yourself. <a href='https://slate.com/news-and-politics/2020/05/george-floyd-protests-police-violence.html?via=recirc_recent'>When unavoidable confrontation happens</a>, you should know how to protect yourself."
locale: en-US

# Build settings
plugins:
  - jekyll-feed

permalink: /:title

sass:
  style: compressed
  load_paths:
    - node_modules/
  
exclude:
  - README.md
  - package.json
  - package-lock.json

# Content grouping
collections:
  resources:
    output: true
    permalink: /:name/
  share:
    output: true
    permalink: /share/:name/
